---
title: "Course Reflection"
about:
  template: jolla
---

**Reflect on your overall experience in this class by describing an interesting idea that you learned, why it was interesting to you, and what it tells you about practicing statistics.** 

One of the most interesting ideas we covered in the course was bias-variance trade-off and how estimators are compared using mean squared error. In Machine Learning, we learned about ridge/lasso regression, and how they work to regularize linear regression models. But, in ML, we only covered the basics of how the bias-varience trade-off meant we could introduce bias to decrease variance in various models. It was interesting to actually derive the mean squared error using the bias and variance of an estimator, and subsequently use it to determine the best estimator to use. 

**Which assessment (homework assignment, recap task, mini-project, or in-class assessment) do you feel you learned the most from? Explain what you learned from this assessment and/or why the assessment was valuable to you.**

I learned the most from assessment 4, where we had a mix of both frequentist and Bayesian-based questions. This assessment forced me to understand the conceptual differences between the two frameworks, as well as be able to apply the techniques to real life examples. In the Bayesian section, we were required to understand both the graph of a prior and posterior distribution and what it can tell us about the data, as well as how to derive a posterior distribution and identify the named distribution associated with it. This assessment also highlighted frequestist strategies, with an example of doing a permutation test and calculating the p-value manually from a set of means. This is a practical example that benefited my understanding of the concept. In addition, it highlighted the calculation of Type I and Type II errors, which are primarily important when applying statistical methods to real-world examples. 

**What was a concept you learned in this course that you hope you remember 5 years from now? Why is it important that you remember this concept?**

I want to remember likelihood functions and maximum likelihood estimation (MLE). As I'm planning on pursuing further education in data science and ideally moving into a career in that field, it is one of the most widely used things we learned over the course of the semester. Likelihood functions were used in both frequentist and Bayesian approaches to problem solving, and understanding how they work to estimate different parameter values given observed data is essential to build, interpret, and compare models. This concept will continue to be necessary in any further statistical or machine learning coursework, and therefore is vital to remember.

**What statistical ideas are you curious to know more about as a result of taking this class? Try to give two examples and explain why you would like to know more about them.**

I would like to know more about Bayesian statistics and how it can be used in real-world applications. The examples we did in class were a great introduction to Bayesian analysis, and I can see how it could be incredibly useful in real-world applications. Like in the miniproject, I liked experimenting with different priors to reflect real-world uncertainty, and want to learn more about how they're used in further data science applications. Another idea I want to learn more about is the use of bootstrap and resampling methods in statistics. These methods are very powerful and can be used to make inferences about populations without relying on traditional assumptions about the data. For example, bootstrapping allows us to estimate the sampling distribution of a statistic by resampling from the data itself, which can be very useful when we have limited data or when the underlying distribution is unknown. This will become helpful in further studies in data science with real-world applications, as real-world data is often messy or lacking. 
