---
title: "Mini-Project Refection"
date: "04-28-2025"
categories:
  - reflection
---

The first mini-project we did involved simulations of the sampling distributions of the sample minimum ($Y_{min}$) and the sample maximum ($Y_{max}$) when taking samples  from different populations (specified below). This connected to the overall goal of section 1, where our goals involved constructing the sampling distribution of any sample statistic (sample mean, sample median, sample maximum, etc.) given a population model for the simulation, explaining how a change in sample size affects the center and spread of a sampling distribution, and matching properties of the simulated sampling distribution of the sample mean to the theoretical sampling distribution of the sample mean that we did in probability. The second mini-project involved writing a story that demonstrated our understanding of terms related to the estimation unit of class. In the story, we had to highlight ideas like bias, variance, estimation, and sampling distributions, and how they connected to one another in a real-life/physical scenario. The third miniproject was based on what happens to interval width and coverage rate if an assumption is violated for the asymptotic confidence interval for a population proportion. This expanded on what we had done in class, as all of the examples we had passed the assumptions, meaning all intervals and coverage rates found were likely valid to estimate confidence intervals. Without having those assumptions, we cannot say the same. This connected directly to Central Limit Theorem and sampling variability. 

The fourth miniproject was a transition from a frequentist model to a Bayesian model of thought. In the miniproject, we were able to compare informative and non-informative priors, showing how prior beliefs influence posterior estimates. This allowed us to see how Bayesian inference can be used to update our beliefs about a parameter based on new data, which is a key concept in statistics. The fifth miniproject went back to the frequentist model of statistics, and involved examining the use and limitations of p-values and their current significance in statistics. It succeeded in connecting significance theory to real-world statistical ethics and communication, and also allowed us to think about the implications of the work we when using p-values for hypothesis testing. As a result, we were able to formulate opinions on the the current statistical significance versus practical significance of p-values, and how we might adjust the perspective of the statistical community as a whole.

Thinking about how miniprojects connected to eachother, miniprojects 1, 3, and 4 all required us to simulate during the assignment, which highlighted how improtant approixmation is to statistics and how much we rely on it. Instead of simulating a statistical scenario, miniprojects 2 and 5 were examples of how we might need to communicate our understanding of statistical concepts through words and explanation, rather than math. These two projects emphasized the importance of clear communication in statistics, as it is not just about the math, but also about conveying the reasoning and implications behind the numbers. Miniprojects 3 and 5 also connected through talking about confidence and uncertainty in statistics. With miniproject 3 highlighting confidence through intervals, while miniproject 5 highlighted thr broader implications of quantifying uncertainty with the current standards. Finally we can think about how miniproject 4 offered a Bayesian contrast to the frequentist ideas explored in miniprojects 3 (CI coverage) and 5 (p-values). 

Overall, the miniprojects in this course were essential in helping us to learn statistical concepts in a way that was different to a homework or graded in class assessment. The miniprojects allowed us to grasp key concepts through practical applications. Each of the five sections of the course had an associated miniproject that allowed us to build on our understanding from the unit, as well as reflect on connections from other sections not directly connceted. From miniproject 1, we can take away that statistical theory and simulation work together. From miniprojects 2 and 5, we can conclude that clear statistical communication is vital to the study of statistics, both for understanding and later research. From miniprojects 3 and 4, we can think about how Bayesian statistics can provide an alternate approach to uncertainty, contrasting it with the use of uncertainty in the frequentist perspective. Both are good, but each has diffreent benefits and drawbacks to their use. 
